/**
 * Represents a food item in the database.
 * This entity maps to the 'foods' table in PostgreSQL.
 */
import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
} from 'typeorm'

@Entity({ name: 'foods' })
export class Food {
  /**
   * Unique identifier for the food item.
   * Auto-generated by the database.
   */
  @PrimaryGeneratedColumn()
  id!: number

  /**
   * External reference number for the food item.
   * Corresponds to Livsmedelsverket's ID.
   */
  @Column()
  number!: string

  /**
   * Name of the food item.
   */
  @Column()
  name!: string

  /**
   * Timestamp when the food item was created in the database.
   */
  @CreateDateColumn({ name: 'created_at' })
  createdAt!: Date
}
