name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checka ut koden
        uses: actions/checkout@v3

      - name: Installera Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Installera Newman
        run: npm install -g newman

      - name: Kör Newman-tester
        run: newman run 'Livsmedel GraphQL API Tests.postman_collection.json' -e 'Livsmedel API - Production Environment.postman_environment.json'

      - name: Konfigurera SSH
        if: ${{ success() }}
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Lägg till SSH fingerprint för server
        if: ${{ success() }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy till VPS
        if: ${{ success() }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /var/www/angelicamarker.online
            git pull
            docker-compose down
            docker-compose build
            docker-compose up -d
          EOF
